#!/bin/bash -e

if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp"
fi

dry_run=0;
debug=0;
while getopts ":t:d" opt; do
    case $opt in
        t)
            dry_run=1;
            ;;
        d)
            debug=1;
            ;;
        \?)
            ;;
    esac
done

function install_puppet() {
    printf "Installing puppet..."
    curl -sS http://apt.puppetlabs.com/puppetlabs-release-jessie.deb > $TMPDIR/puppetlabs-release-jessie.deb
    sudo dpkg -i $TMPDIR/puppetlabs-release-jessie.deb
    sudo apt-get update
    sudo apt-get install -y puppet
    cp /etc/puppet/puppet.conf $TMPDIR/puppet.conf
    echo '[main]
logdir=/var/log/puppet
vardir=/var/lib/puppet
ssldir=/var/lib/puppet/ssl
rundir=/var/run/puppet
factpath=$confdir/facter
' | sudo tee /etc/puppet/puppet.conf

}

install_puppet_modules() {
    sudo puppet module install puppetlabs-apt --version 2.4.0
    sudo puppet module install garethr-docker
    sudo puppet module install puppetlabs-git
    sudo puppet module install maestrodev/wget
}

apply() {
    flags="--verbose"
    if [[ $dry_run -eq 1 ]]; then
        flags="${flags} --test"
    fi
    if [[ $debug -eq 1 ]]; then
        flags="${flags} --debug"
    fi

    sudo puppet apply ${flags} "$1"
}

zsh=$(which zsh)
if [[ "$SHELL" != "$zsh" ]]; then
   echo "Setting default shell to zsh:"
   chsh -s "$zsh"
fi

command_exists puppet || install_puppet

install_puppet_modules

apply ".puppet/manifests/base.pp"
